### ISSUE TITLE
Aggiornare la pagina "sala stampa" per contenere link a menzioni e articoli interessanti

### ISSUE THREAD

**Issue by smaffulli** [PartitoPirata/www#5]
Su richiesta del segretario @Deme-among ho preparato un prototipo per la pagina di sommario delle attività recenti del partito. Al momento la pagina [sala stampa](https://partito-pirata.it/sala-stampa) ha vari problemi:

1. troppa enfasi su comunicati stampa che il partito non sta facendo
2. mancanza di uno spazio per inserire link ad articoli scritti da membri del partito oppure articoli in cui membri del partito sono intervistati

Per ovviare al punto 2, bisogna aggiungere a wordpress un sistema di gestione e organizzazione di link. Il punto 1 si risolve producendo nuovi comunicati, oppure spostando in fondo alla pagina i contenuti vecchi e alzando il blog che stiamo usando di più.

**Comment by GiuseppeChillemi** [comment]
A me piace molto come idea. Posso contribuire aggiungendo Link

**Comment by smaffulli** [comment]
Ho fatto un prototipo sul sito di test che penso possa funzionare. Ho usato il plugin che è già installato, Link Library `wp-admin/edit.php?post_type=link_library_links`

Il risultato finale somiglia a questo:

![image](https://user-images.githubusercontent.com/1348736/115086734-1fb0be00-9f0d-11eb-9920-65ca867d0710.png)

Ho creato una collezione nuova chiamata RassegnaStampa e configurato il CSS in modo che non faccia troppo schifo (il default è da vomito). 

La parte che non mi convince ancora al 100% è la paginazione dei link: mi pare che passando alle pagine seguenti si creino degli artifatti poco belli.

Se il layout sembra funzionare, direi che possiamo passare a inserire un po' di link sul sito di produzione prima di attivare il blocco e sistemare la pagina sala stampa. 

Commenti?

**Comment by smaffulli** [comment]
Per inserire nuovi  link parti da `/wp-admin/post-new.php?post_type=link_library_links` e segui le istruzioni qui sotto:

![image](https://user-images.githubusercontent.com/1348736/115088557-b763db80-9f10-11eb-9c54-b303a52ba1f0.png)

**Comment by GiuseppeChillemi** [comment]
Lo trovo poco funzionale. Preferisco un sistema sviluppato in orizzontale come questo:

![image](https://user-images.githubusercontent.com/1828237/115088721-1c1f3600-9f11-11eb-9054-73b5f2c2bf30.png)

Con le seguenti modifiche:

Prima colonna deve essere SOURCE
Aggiungere un seconda colonna TYPE con i TAG 
Terza, il titolo dell'articolo
Se possibile, sotto il titolo vanno 3 righe prese da esso o inserite da noi.

**Comment by GiuseppeChillemi** [comment]
Dimenticavo, i TAG e le Sorgenti devono potere fare da raggruppatore, esempio:

![image](https://user-images.githubusercontent.com/1828237/115089046-c72fef80-9f11-11eb-894b-0b5d6b239988.png)

Oltre a "LATEST" potresti raggruppare per tag come "COPYRIGHT, POLITICS" etc...

**Comment by Deme-among** [comment]
A me piace come viene la pagina fatta da Stefano. Non mi piace la proposta tipo elenco di Chillemi. Per il resto non capisco nulla di ciò che avete scritto. A me interessa che sul sito ci sia un posto dove posso inserire articoli interessanti per il nostro dibattito politico e valorizzare le cose scritte da pirati iscritti e pubblicate altrove.

**Comment by GiuseppeChillemi** [comment]
a me non piace perché una lista con 3 news in orizzontale impone di scorrere da desta a sinistra e poi da su in giu’. E’ molta più fatica. Sarebbe bello se il plugin contenesse più possibilità di visualizzazione.

**Comment by smaffulli** [comment]
Il plugin offre anche altre possibilità di visualizzazione ma il problema mi pare sia che la visualizzazione che ho messo ora io non funziona bene. Avete provato? @exedre ci puoi dare un'occhiata anche tu per favore? https://testwww.partito-pirata.it/sala-stampa/ per vederlo live

**Comment by Deme-among** [comment]
@smaffulli @exedre novità su questo?

**Comment by exedre** [comment]
A me la pagina di stefano piace e mi sembra raggiunga bene l'obiettivo. C'è solo questo problema andando alla seconda pagina (anche con Successivo): gli articoli scappano tutti sulla destra (provato con Chrome, Firefox e Safari)

![image](https://user-images.githubusercontent.com/82950/116664447-c62ea180-a998-11eb-87be-33e670860329.png)

![image](https://user-images.githubusercontent.com/82950/116664572-f5dda980-a998-11eb-808e-302d4d6006d2.png)

**Comment by smaffulli** [comment]
il plugin ha un po' di cose che non funzionano e non riesco ad aggiustare. Per esempio, non capisco perchè non mostra piú il testo in blocchi...
Purtroppo non ho trovato proprio niente di meglio. Per ora direi andiamo avanti con questo e speriamo che le versioni future del plugin risolvano i problemi. Ho portato il plugin in produzione, si possono aggiungere altri link come da istruzioni.
