### ISSUE TITLE
Preparare il sito per l'assemblea tematica del 28 aprile (questione catalana)

### ISSUE THREAD

**Issue by smaffulli** [PartitoPirata/www#6]
- Modificare l'hero della home page con link alla pagina dell'assemblea
- Creare la pagina dell'assemblea https://www.partito-pirata.it/eventi/il-mercoledi-dei-pirati-2021-04-28/

@Deme-among le immagini le ho. Puoi aggiungere nei commenti per favore:
- il testo da usare nella pagina dell'evento, una descrizione di 200 parole andrebbe bene 
- la lista dei relatori in formato testo 
- un sottotitolo da mettere in home page al posto di `diritto e ragioni` (vedi bozza https://www.partito-pirata.it/partito-pirata-italiano-assemblea-catalogna-ed-europa/)

**Comment by Deme-among** [comment]
- Le vicende catalane degli ultimi anni pongono una serie di questioni  "spinose", che vanno oramai anche al di là della semplice questione separatista. La risposta del governo spagnolo al referendum, il processo, le dure condanne inflitte agli attivisti  politici catalani, la persecuzione dei parlamentari europei catalani ai  quali lo stesso Parlamento europeo ha revocato l'immunità  pongono una serie di problemi che riguardano gli assetti istituzionali degli stati nazionali, il ruolo dell'Unione europea, ma anche l'uso della forza contro "reati politici" e in fondo  la mai risolta dicotomia tra la legalità e i diritti, che appare sempre più evidente anche nelle democrazie occidentali.
-

- ASSEMBLEA PUBBLICA DEL PARTITO PIRATA ITALIANO
Mercoledì 28 aprile 2021, ore 19.00-20.30

Catalogna ed Europa : Diritto e ragioni

●	Antoni  Comín i Oliveres,  parlamentare europeo catalano
●	Francesco Ferraiuolo, professore di Diritto costituzionale, Università “Federico II” di Napoli
●	Francesco Olivo, redattore de La Stampa
●	Matteo Angioli, vice presidente consiglio generale Partito Radicale
●	Introduce e modera: Maria Rosaria lo Muzio, segretario del Partito Pirata Italiano

In home page ci va il titolo per intero secondo me "Catalogna ed Europa: Diritto e ragioni" (attenzione che le maiuscole vanno proprio così)
se poi vuoi un sottotitolo puoi mettere: conversazioni sulla questione catalana e non solo

**Comment by Deme-among** [comment]
ERRATA CORRIGE **Gennaro Ferraiuolo**

**Comment by Deme-among** [comment]
**ERRATA CORRIGE** 
Le vicende catalane degli ultimi anni pongono una serie di questioni "spinose", che vanno oramai anche al di là della pur non semplice causa separatista. La risposta del governo spagnolo al referendum per l'indipendenza, il processo che ne è seguito con  le dure condanne inflitte agli attivisti politici catalani, la perdurante persecuzione dei parlamentari europei catalani ai quali, su richiesta del governo spagnolo,  lo stesso Parlamento europeo ha revocato l'immunità mettono in luce  una serie di problemi che riguardano molti e diversi temi da quello degli assetti territoriali degli stati nazionali al  ruolo dell'Unione europea, ma anche l'uso sproporzionato della forza contro "reati politici" e in fondo la mai risolta dicotomia tra la legalità e i diritti, che appare sempre più evidente anche nelle democrazie occidentali.

**Comment by Deme-among** [comment]
vanno inseriti, in fondo,  i due link agli articoli sull'argomento che ho scritto e sono nel blog
https://www.partito-pirata.it/2021/03/01/leuropa-ha-un-problema-si-chiama-spagna/

https://www.partito-pirata.it/2020/12/17/lo-strano-caso-dei-deputati-catalani-nel-parlamento-europeo/

**Comment by Deme-among** [comment]
Ho fatto una bozza dell'evento sul sito. Non so neanche se tu possa vederla. Mi serviva fare una prova

**Comment by Deme-among** [comment]
va inserito anche questo link

http://globalcommitteefortheruleoflaw.org/it/catalogna-ed-europa-diritto-e-ragioni/

**Comment by smaffulli** [comment]
Per revisione: 

- home page https://www.partito-pirata.it/partito-pirata-italiano-assemblea-catalogna-ed-europa/ 
- pagina dell'assemblea https://www.partito-pirata.it/eventi/catalogna-europa/
